// megafunction wizard: %FIFO%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: dcfifo_mixed_widths 

// ============================================================
// File Name: fifo_32w8r.v
// Megafunction Name(s):
// 			dcfifo_mixed_widths
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.1.0 Build 162 10/23/2013 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2013 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//dcfifo_mixed_widths DEVICE_FAMILY="Cyclone IV E" LPM_NUMWORDS=512 LPM_SHOWAHEAD="OFF" LPM_WIDTH=32 LPM_WIDTH_R=8 LPM_WIDTHU=9 LPM_WIDTHU_R=11 OVERFLOW_CHECKING="ON" RDSYNC_DELAYPIPE=3 READ_ACLR_SYNCH="OFF" UNDERFLOW_CHECKING="ON" USE_EAB="ON" WRITE_ACLR_SYNCH="ON" WRSYNC_DELAYPIPE=3 aclr data q rdclk rdreq wrclk wrempty wrfull wrreq wrusedw INTENDED_DEVICE_FAMILY="Cyclone IV E" ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 13.1 cbx_a_gray2bin 2013:10:23:18:05:48:SJ cbx_a_graycounter 2013:10:23:18:05:48:SJ cbx_altdpram 2013:10:23:18:05:48:SJ cbx_altsyncram 2013:10:23:18:05:48:SJ cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_dcfifo 2013:10:23:18:05:48:SJ cbx_fifo_common 2013:10:23:18:05:48:SJ cbx_lpm_add_sub 2013:10:23:18:05:48:SJ cbx_lpm_compare 2013:10:23:18:05:48:SJ cbx_lpm_counter 2013:10:23:18:05:48:SJ cbx_lpm_decode 2013:10:23:18:05:48:SJ cbx_lpm_mux 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_scfifo 2013:10:23:18:05:48:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ cbx_stratixiii 2013:10:23:18:05:48:SJ cbx_stratixv 2013:10:23:18:05:48:SJ cbx_util_mgl 2013:10:23:18:05:48:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//a_gray2bin device_family="Cyclone IV E" WIDTH=10 bin gray
//VERSION_BEGIN 13.1 cbx_a_gray2bin 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fifo_32w8r_a_gray2bin
	( 
	bin,
	gray) /* synthesis synthesis_clearbox=1 */;
	output   [9:0]  bin;
	input   [9:0]  gray;

	wire  xor0;
	wire  xor1;
	wire  xor2;
	wire  xor3;
	wire  xor4;
	wire  xor5;
	wire  xor6;
	wire  xor7;
	wire  xor8;

	assign
		bin = {gray[9], xor8, xor7, xor6, xor5, xor4, xor3, xor2, xor1, xor0},
		xor0 = (gray[0] ^ xor1),
		xor1 = (gray[1] ^ xor2),
		xor2 = (gray[2] ^ xor3),
		xor3 = (gray[3] ^ xor4),
		xor4 = (gray[4] ^ xor5),
		xor5 = (gray[5] ^ xor6),
		xor6 = (gray[6] ^ xor7),
		xor7 = (gray[7] ^ xor8),
		xor8 = (gray[9] ^ gray[8]);
endmodule //fifo_32w8r_a_gray2bin


//a_graycounter DEVICE_FAMILY="Cyclone IV E" PVALUE=0 WIDTH=10 aclr clock cnt_en q
//VERSION_BEGIN 13.1 cbx_a_gray2bin 2013:10:23:18:05:48:SJ cbx_a_graycounter 2013:10:23:18:05:48:SJ cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ  VERSION_END

//synthesis_resources = reg 14 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"{-to sub_parity4a[0]} POWER_UP_LEVEL=HIGH"} *)
module  fifo_32w8r_a_graycounter
	( 
	aclr,
	clock,
	cnt_en,
	q) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clock;
	input   cnt_en;
	output   [9:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[9:0]	counter5a;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=LOW"} *)
	reg	parity3;
	reg	[2:0]	sub_parity4a;
	wire  [9:0]  cntr_cout;
	wire  parity_cout;
	wire sclr;
	wire updown;

	// synopsys translate_off
	initial
		counter5a[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[0:0] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[0:0] <= 1'b0;
			else  counter5a[0:0] <= ((cnt_en & (counter5a[0:0] ^ (~ parity_cout))) | ((~ cnt_en) & counter5a[0:0]));
	// synopsys translate_off
	initial
		counter5a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[1:1] <= 1'b0;
			else  counter5a[1:1] <= (counter5a[1:1] ^ (counter5a[0:0] & cntr_cout[0]));
	// synopsys translate_off
	initial
		counter5a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[2:2] <= 1'b0;
			else  counter5a[2:2] <= (counter5a[2:2] ^ (counter5a[1:1] & cntr_cout[1]));
	// synopsys translate_off
	initial
		counter5a[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[3:3] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[3:3] <= 1'b0;
			else  counter5a[3:3] <= (counter5a[3:3] ^ (counter5a[2:2] & cntr_cout[2]));
	// synopsys translate_off
	initial
		counter5a[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[4:4] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[4:4] <= 1'b0;
			else  counter5a[4:4] <= (counter5a[4:4] ^ (counter5a[3:3] & cntr_cout[3]));
	// synopsys translate_off
	initial
		counter5a[5:5] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[5:5] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[5:5] <= 1'b0;
			else  counter5a[5:5] <= (counter5a[5:5] ^ (counter5a[4:4] & cntr_cout[4]));
	// synopsys translate_off
	initial
		counter5a[6:6] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[6:6] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[6:6] <= 1'b0;
			else  counter5a[6:6] <= (counter5a[6:6] ^ (counter5a[5:5] & cntr_cout[5]));
	// synopsys translate_off
	initial
		counter5a[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[7:7] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[7:7] <= 1'b0;
			else  counter5a[7:7] <= (counter5a[7:7] ^ (counter5a[6:6] & cntr_cout[6]));
	// synopsys translate_off
	initial
		counter5a[8:8] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[8:8] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[8:8] <= 1'b0;
			else  counter5a[8:8] <= (counter5a[8:8] ^ (counter5a[7:7] & cntr_cout[7]));
	// synopsys translate_off
	initial
		counter5a[9:9] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[9:9] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[9:9] <= 1'b0;
			else  counter5a[9:9] <= (counter5a[9:9] ^ cntr_cout[8]);
	// synopsys translate_off
	initial
		parity3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) parity3 <= 1'b0;
		else
			if (sclr == 1'b1) parity3 <= 1'b0;
			else  parity3 <= ((cnt_en & ((sub_parity4a[0] ^ sub_parity4a[1]) ^ sub_parity4a[2])) | ((~ cnt_en) & parity3));
	// synopsys translate_off
	initial
		sub_parity4a[0:0] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity4a[0:0] <= {1{1'b1}};
		else
			if (sclr == 1'b1) sub_parity4a[0:0] <= 1'b0;
			else  sub_parity4a[0:0] <= ((cnt_en & (((counter5a[0] ^ counter5a[1]) ^ counter5a[2]) ^ counter5a[3])) | ((~ cnt_en) & sub_parity4a[0:0]));
	// synopsys translate_off
	initial
		sub_parity4a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity4a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity4a[1:1] <= 1'b0;
			else  sub_parity4a[1:1] <= ((cnt_en & (((counter5a[4] ^ counter5a[5]) ^ counter5a[6]) ^ counter5a[7])) | ((~ cnt_en) & sub_parity4a[1:1]));
	// synopsys translate_off
	initial
		sub_parity4a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity4a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity4a[2:2] <= 1'b0;
			else  sub_parity4a[2:2] <= ((cnt_en & (counter5a[8] ^ counter5a[9])) | ((~ cnt_en) & sub_parity4a[2:2]));
	assign
		cntr_cout = {1'b0, (cntr_cout[7] & (~ counter5a[7:7])), (cntr_cout[6] & (~ counter5a[6:6])), (cntr_cout[5] & (~ counter5a[5:5])), (cntr_cout[4] & (~ counter5a[4:4])), (cntr_cout[3] & (~ counter5a[3:3])), (cntr_cout[2] & (~ counter5a[2:2])), (cntr_cout[1] & (~ counter5a[1:1])), (cntr_cout[0] & (~ counter5a[0:0])), (cnt_en & parity_cout)},
		parity_cout = ((parity3 ^ (~ updown)) & cnt_en),
		q = counter5a,
		sclr = 1'b0,
		updown = 1'b1;
endmodule //fifo_32w8r_a_graycounter


//a_graycounter DEVICE_FAMILY="Cyclone IV E" PVALUE=1 WIDTH=10 aclr clock cnt_en q ALTERA_INTERNAL_OPTIONS=suppress_da_rule_internal=S102
//VERSION_BEGIN 13.1 cbx_a_gray2bin 2013:10:23:18:05:48:SJ cbx_a_graycounter 2013:10:23:18:05:48:SJ cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ  VERSION_END

//synthesis_resources = reg 14 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"suppress_da_rule_internal=S102;{-to counter6a[0]} POWER_UP_LEVEL=HIGH"} *)
module  fifo_32w8r_a_graycounter1
	( 
	aclr,
	clock,
	cnt_en,
	q) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clock;
	input   cnt_en;
	output   [9:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[9:0]	counter6a;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	parity7;
	reg	[2:0]	sub_parity8a;
	wire  [9:0]  cntr_cout;
	wire  parity_cout;
	wire sclr;
	wire updown;

	// synopsys translate_off
	initial
		counter6a[0:0] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[0:0] <= {1{1'b1}};
		else
			if (sclr == 1'b1) counter6a[0:0] <= 1'b0;
			else  counter6a[0:0] <= ((cnt_en & (counter6a[0:0] ^ (~ parity_cout))) | ((~ cnt_en) & counter6a[0:0]));
	// synopsys translate_off
	initial
		counter6a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) counter6a[1:1] <= 1'b0;
			else  counter6a[1:1] <= (counter6a[1:1] ^ (counter6a[0:0] & cntr_cout[0]));
	// synopsys translate_off
	initial
		counter6a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) counter6a[2:2] <= 1'b0;
			else  counter6a[2:2] <= (counter6a[2:2] ^ (counter6a[1:1] & cntr_cout[1]));
	// synopsys translate_off
	initial
		counter6a[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[3:3] <= 1'b0;
		else
			if (sclr == 1'b1) counter6a[3:3] <= 1'b0;
			else  counter6a[3:3] <= (counter6a[3:3] ^ (counter6a[2:2] & cntr_cout[2]));
	// synopsys translate_off
	initial
		counter6a[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[4:4] <= 1'b0;
		else
			if (sclr == 1'b1) counter6a[4:4] <= 1'b0;
			else  counter6a[4:4] <= (counter6a[4:4] ^ (counter6a[3:3] & cntr_cout[3]));
	// synopsys translate_off
	initial
		counter6a[5:5] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[5:5] <= 1'b0;
		else
			if (sclr == 1'b1) counter6a[5:5] <= 1'b0;
			else  counter6a[5:5] <= (counter6a[5:5] ^ (counter6a[4:4] & cntr_cout[4]));
	// synopsys translate_off
	initial
		counter6a[6:6] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[6:6] <= 1'b0;
		else
			if (sclr == 1'b1) counter6a[6:6] <= 1'b0;
			else  counter6a[6:6] <= (counter6a[6:6] ^ (counter6a[5:5] & cntr_cout[5]));
	// synopsys translate_off
	initial
		counter6a[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[7:7] <= 1'b0;
		else
			if (sclr == 1'b1) counter6a[7:7] <= 1'b0;
			else  counter6a[7:7] <= (counter6a[7:7] ^ (counter6a[6:6] & cntr_cout[6]));
	// synopsys translate_off
	initial
		counter6a[8:8] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[8:8] <= 1'b0;
		else
			if (sclr == 1'b1) counter6a[8:8] <= 1'b0;
			else  counter6a[8:8] <= (counter6a[8:8] ^ (counter6a[7:7] & cntr_cout[7]));
	// synopsys translate_off
	initial
		counter6a[9:9] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter6a[9:9] <= 1'b0;
		else
			if (sclr == 1'b1) counter6a[9:9] <= 1'b0;
			else  counter6a[9:9] <= (counter6a[9:9] ^ cntr_cout[8]);
	// synopsys translate_off
	initial
		parity7 = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) parity7 <= {1{1'b1}};
		else
			if (sclr == 1'b1) parity7 <= 1'b0;
			else  parity7 <= ((cnt_en & ((sub_parity8a[0] ^ sub_parity8a[1]) ^ sub_parity8a[2])) | ((~ cnt_en) & parity7));
	// synopsys translate_off
	initial
		sub_parity8a[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity8a[0:0] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity8a[0:0] <= 1'b0;
			else  sub_parity8a[0:0] <= ((cnt_en & (((counter6a[0] ^ counter6a[1]) ^ counter6a[2]) ^ counter6a[3])) | ((~ cnt_en) & sub_parity8a[0:0]));
	// synopsys translate_off
	initial
		sub_parity8a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity8a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity8a[1:1] <= 1'b0;
			else  sub_parity8a[1:1] <= ((cnt_en & (((counter6a[4] ^ counter6a[5]) ^ counter6a[6]) ^ counter6a[7])) | ((~ cnt_en) & sub_parity8a[1:1]));
	// synopsys translate_off
	initial
		sub_parity8a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sub_parity8a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) sub_parity8a[2:2] <= 1'b0;
			else  sub_parity8a[2:2] <= ((cnt_en & (counter6a[8] ^ counter6a[9])) | ((~ cnt_en) & sub_parity8a[2:2]));
	assign
		cntr_cout = {1'b0, (cntr_cout[7] & (~ counter6a[7:7])), (cntr_cout[6] & (~ counter6a[6:6])), (cntr_cout[5] & (~ counter6a[5:5])), (cntr_cout[4] & (~ counter6a[4:4])), (cntr_cout[3] & (~ counter6a[3:3])), (cntr_cout[2] & (~ counter6a[2:2])), (cntr_cout[1] & (~ counter6a[1:1])), (cntr_cout[0] & (~ counter6a[0:0])), (cnt_en & parity_cout)},
		parity_cout = (((~ parity7) ^ updown) & cnt_en),
		q = counter6a,
		sclr = 1'b0,
		updown = 1'b1;
endmodule //fifo_32w8r_a_graycounter1


//altsyncram ADDRESS_ACLR_B="CLEAR1" ADDRESS_REG_B="CLOCK1" CLOCK_ENABLE_INPUT_B="BYPASS" DEVICE_FAMILY="Cyclone IV E" OPERATION_MODE="DUAL_PORT" OUTDATA_ACLR_B="CLEAR1" OUTDATA_REG_B="CLOCK1" WIDTH_A=32 WIDTH_B=8 WIDTH_BYTEENA_A=1 WIDTHAD_A=9 WIDTHAD_B=11 aclr1 address_a address_b addressstall_b clock0 clock1 clocken1 data_a q_b wren_a
//VERSION_BEGIN 13.1 cbx_altsyncram 2013:10:23:18:05:48:SJ cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_lpm_add_sub 2013:10:23:18:05:48:SJ cbx_lpm_compare 2013:10:23:18:05:48:SJ cbx_lpm_decode 2013:10:23:18:05:48:SJ cbx_lpm_mux 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ cbx_stratixiii 2013:10:23:18:05:48:SJ cbx_stratixv 2013:10:23:18:05:48:SJ cbx_util_mgl 2013:10:23:18:05:48:SJ  VERSION_END

//synthesis_resources = M9K 2 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  fifo_32w8r_altsyncram
	( 
	aclr1,
	address_a,
	address_b,
	addressstall_b,
	clock0,
	clock1,
	clocken1,
	data_a,
	q_b,
	wren_a) /* synthesis synthesis_clearbox=1 */;
	input   aclr1;
	input   [8:0]  address_a;
	input   [10:0]  address_b;
	input   addressstall_b;
	input   clock0;
	input   clock1;
	input   clocken1;
	input   [31:0]  data_a;
	output   [7:0]  q_b;
	input   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr1;
	tri1   [10:0]  address_b;
	tri0   addressstall_b;
	tri1   clock0;
	tri1   clock1;
	tri1   clocken1;
	tri1   [31:0]  data_a;
	tri0   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block9a_0portbdataout;
	wire  [0:0]   wire_ram_block9a_1portbdataout;
	wire  [0:0]   wire_ram_block9a_2portbdataout;
	wire  [0:0]   wire_ram_block9a_3portbdataout;
	wire  [0:0]   wire_ram_block9a_4portbdataout;
	wire  [0:0]   wire_ram_block9a_5portbdataout;
	wire  [0:0]   wire_ram_block9a_6portbdataout;
	wire  [0:0]   wire_ram_block9a_7portbdataout;
	wire  [8:0]  address_a_wire;
	wire  [10:0]  address_b_wire;

	cycloneive_ram_block   ram_block9a_0
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[8:0]}),
	.portadatain({data_a[24], data_a[16], data_a[8], data_a[0]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[10:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block9a_0portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block9a_0.clk0_core_clock_enable = "ena0",
		ram_block9a_0.clk0_input_clock_enable = "none",
		ram_block9a_0.clk1_core_clock_enable = "none",
		ram_block9a_0.clk1_input_clock_enable = "none",
		ram_block9a_0.clk1_output_clock_enable = "ena1",
		ram_block9a_0.connectivity_checking = "OFF",
		ram_block9a_0.data_interleave_offset_in_bits = 8,
		ram_block9a_0.data_interleave_width_in_bits = 1,
		ram_block9a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block9a_0.mixed_port_feed_through_mode = "dont_care",
		ram_block9a_0.operation_mode = "dual_port",
		ram_block9a_0.port_a_address_width = 9,
		ram_block9a_0.port_a_data_width = 4,
		ram_block9a_0.port_a_first_address = 0,
		ram_block9a_0.port_a_first_bit_number = 0,
		ram_block9a_0.port_a_last_address = 511,
		ram_block9a_0.port_a_logical_ram_depth = 512,
		ram_block9a_0.port_a_logical_ram_width = 32,
		ram_block9a_0.port_b_address_clear = "clear1",
		ram_block9a_0.port_b_address_clock = "clock1",
		ram_block9a_0.port_b_address_width = 11,
		ram_block9a_0.port_b_data_out_clear = "clear1",
		ram_block9a_0.port_b_data_out_clock = "clock1",
		ram_block9a_0.port_b_data_width = 1,
		ram_block9a_0.port_b_first_address = 0,
		ram_block9a_0.port_b_first_bit_number = 0,
		ram_block9a_0.port_b_last_address = 2047,
		ram_block9a_0.port_b_logical_ram_depth = 2048,
		ram_block9a_0.port_b_logical_ram_width = 8,
		ram_block9a_0.port_b_read_enable_clock = "clock1",
		ram_block9a_0.ram_block_type = "AUTO",
		ram_block9a_0.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block9a_1
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[8:0]}),
	.portadatain({data_a[25], data_a[17], data_a[9], data_a[1]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[10:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block9a_1portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block9a_1.clk0_core_clock_enable = "ena0",
		ram_block9a_1.clk0_input_clock_enable = "none",
		ram_block9a_1.clk1_core_clock_enable = "none",
		ram_block9a_1.clk1_input_clock_enable = "none",
		ram_block9a_1.clk1_output_clock_enable = "ena1",
		ram_block9a_1.connectivity_checking = "OFF",
		ram_block9a_1.data_interleave_offset_in_bits = 8,
		ram_block9a_1.data_interleave_width_in_bits = 1,
		ram_block9a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block9a_1.mixed_port_feed_through_mode = "dont_care",
		ram_block9a_1.operation_mode = "dual_port",
		ram_block9a_1.port_a_address_width = 9,
		ram_block9a_1.port_a_data_width = 4,
		ram_block9a_1.port_a_first_address = 0,
		ram_block9a_1.port_a_first_bit_number = 1,
		ram_block9a_1.port_a_last_address = 511,
		ram_block9a_1.port_a_logical_ram_depth = 512,
		ram_block9a_1.port_a_logical_ram_width = 32,
		ram_block9a_1.port_b_address_clear = "clear1",
		ram_block9a_1.port_b_address_clock = "clock1",
		ram_block9a_1.port_b_address_width = 11,
		ram_block9a_1.port_b_data_out_clear = "clear1",
		ram_block9a_1.port_b_data_out_clock = "clock1",
		ram_block9a_1.port_b_data_width = 1,
		ram_block9a_1.port_b_first_address = 0,
		ram_block9a_1.port_b_first_bit_number = 1,
		ram_block9a_1.port_b_last_address = 2047,
		ram_block9a_1.port_b_logical_ram_depth = 2048,
		ram_block9a_1.port_b_logical_ram_width = 8,
		ram_block9a_1.port_b_read_enable_clock = "clock1",
		ram_block9a_1.ram_block_type = "AUTO",
		ram_block9a_1.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block9a_2
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[8:0]}),
	.portadatain({data_a[26], data_a[18], data_a[10], data_a[2]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[10:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block9a_2portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block9a_2.clk0_core_clock_enable = "ena0",
		ram_block9a_2.clk0_input_clock_enable = "none",
		ram_block9a_2.clk1_core_clock_enable = "none",
		ram_block9a_2.clk1_input_clock_enable = "none",
		ram_block9a_2.clk1_output_clock_enable = "ena1",
		ram_block9a_2.connectivity_checking = "OFF",
		ram_block9a_2.data_interleave_offset_in_bits = 8,
		ram_block9a_2.data_interleave_width_in_bits = 1,
		ram_block9a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block9a_2.mixed_port_feed_through_mode = "dont_care",
		ram_block9a_2.operation_mode = "dual_port",
		ram_block9a_2.port_a_address_width = 9,
		ram_block9a_2.port_a_data_width = 4,
		ram_block9a_2.port_a_first_address = 0,
		ram_block9a_2.port_a_first_bit_number = 2,
		ram_block9a_2.port_a_last_address = 511,
		ram_block9a_2.port_a_logical_ram_depth = 512,
		ram_block9a_2.port_a_logical_ram_width = 32,
		ram_block9a_2.port_b_address_clear = "clear1",
		ram_block9a_2.port_b_address_clock = "clock1",
		ram_block9a_2.port_b_address_width = 11,
		ram_block9a_2.port_b_data_out_clear = "clear1",
		ram_block9a_2.port_b_data_out_clock = "clock1",
		ram_block9a_2.port_b_data_width = 1,
		ram_block9a_2.port_b_first_address = 0,
		ram_block9a_2.port_b_first_bit_number = 2,
		ram_block9a_2.port_b_last_address = 2047,
		ram_block9a_2.port_b_logical_ram_depth = 2048,
		ram_block9a_2.port_b_logical_ram_width = 8,
		ram_block9a_2.port_b_read_enable_clock = "clock1",
		ram_block9a_2.ram_block_type = "AUTO",
		ram_block9a_2.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block9a_3
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[8:0]}),
	.portadatain({data_a[27], data_a[19], data_a[11], data_a[3]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[10:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block9a_3portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block9a_3.clk0_core_clock_enable = "ena0",
		ram_block9a_3.clk0_input_clock_enable = "none",
		ram_block9a_3.clk1_core_clock_enable = "none",
		ram_block9a_3.clk1_input_clock_enable = "none",
		ram_block9a_3.clk1_output_clock_enable = "ena1",
		ram_block9a_3.connectivity_checking = "OFF",
		ram_block9a_3.data_interleave_offset_in_bits = 8,
		ram_block9a_3.data_interleave_width_in_bits = 1,
		ram_block9a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block9a_3.mixed_port_feed_through_mode = "dont_care",
		ram_block9a_3.operation_mode = "dual_port",
		ram_block9a_3.port_a_address_width = 9,
		ram_block9a_3.port_a_data_width = 4,
		ram_block9a_3.port_a_first_address = 0,
		ram_block9a_3.port_a_first_bit_number = 3,
		ram_block9a_3.port_a_last_address = 511,
		ram_block9a_3.port_a_logical_ram_depth = 512,
		ram_block9a_3.port_a_logical_ram_width = 32,
		ram_block9a_3.port_b_address_clear = "clear1",
		ram_block9a_3.port_b_address_clock = "clock1",
		ram_block9a_3.port_b_address_width = 11,
		ram_block9a_3.port_b_data_out_clear = "clear1",
		ram_block9a_3.port_b_data_out_clock = "clock1",
		ram_block9a_3.port_b_data_width = 1,
		ram_block9a_3.port_b_first_address = 0,
		ram_block9a_3.port_b_first_bit_number = 3,
		ram_block9a_3.port_b_last_address = 2047,
		ram_block9a_3.port_b_logical_ram_depth = 2048,
		ram_block9a_3.port_b_logical_ram_width = 8,
		ram_block9a_3.port_b_read_enable_clock = "clock1",
		ram_block9a_3.ram_block_type = "AUTO",
		ram_block9a_3.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block9a_4
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[8:0]}),
	.portadatain({data_a[28], data_a[20], data_a[12], data_a[4]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[10:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block9a_4portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block9a_4.clk0_core_clock_enable = "ena0",
		ram_block9a_4.clk0_input_clock_enable = "none",
		ram_block9a_4.clk1_core_clock_enable = "none",
		ram_block9a_4.clk1_input_clock_enable = "none",
		ram_block9a_4.clk1_output_clock_enable = "ena1",
		ram_block9a_4.connectivity_checking = "OFF",
		ram_block9a_4.data_interleave_offset_in_bits = 8,
		ram_block9a_4.data_interleave_width_in_bits = 1,
		ram_block9a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block9a_4.mixed_port_feed_through_mode = "dont_care",
		ram_block9a_4.operation_mode = "dual_port",
		ram_block9a_4.port_a_address_width = 9,
		ram_block9a_4.port_a_data_width = 4,
		ram_block9a_4.port_a_first_address = 0,
		ram_block9a_4.port_a_first_bit_number = 4,
		ram_block9a_4.port_a_last_address = 511,
		ram_block9a_4.port_a_logical_ram_depth = 512,
		ram_block9a_4.port_a_logical_ram_width = 32,
		ram_block9a_4.port_b_address_clear = "clear1",
		ram_block9a_4.port_b_address_clock = "clock1",
		ram_block9a_4.port_b_address_width = 11,
		ram_block9a_4.port_b_data_out_clear = "clear1",
		ram_block9a_4.port_b_data_out_clock = "clock1",
		ram_block9a_4.port_b_data_width = 1,
		ram_block9a_4.port_b_first_address = 0,
		ram_block9a_4.port_b_first_bit_number = 4,
		ram_block9a_4.port_b_last_address = 2047,
		ram_block9a_4.port_b_logical_ram_depth = 2048,
		ram_block9a_4.port_b_logical_ram_width = 8,
		ram_block9a_4.port_b_read_enable_clock = "clock1",
		ram_block9a_4.ram_block_type = "AUTO",
		ram_block9a_4.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block9a_5
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[8:0]}),
	.portadatain({data_a[29], data_a[21], data_a[13], data_a[5]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[10:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block9a_5portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block9a_5.clk0_core_clock_enable = "ena0",
		ram_block9a_5.clk0_input_clock_enable = "none",
		ram_block9a_5.clk1_core_clock_enable = "none",
		ram_block9a_5.clk1_input_clock_enable = "none",
		ram_block9a_5.clk1_output_clock_enable = "ena1",
		ram_block9a_5.connectivity_checking = "OFF",
		ram_block9a_5.data_interleave_offset_in_bits = 8,
		ram_block9a_5.data_interleave_width_in_bits = 1,
		ram_block9a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block9a_5.mixed_port_feed_through_mode = "dont_care",
		ram_block9a_5.operation_mode = "dual_port",
		ram_block9a_5.port_a_address_width = 9,
		ram_block9a_5.port_a_data_width = 4,
		ram_block9a_5.port_a_first_address = 0,
		ram_block9a_5.port_a_first_bit_number = 5,
		ram_block9a_5.port_a_last_address = 511,
		ram_block9a_5.port_a_logical_ram_depth = 512,
		ram_block9a_5.port_a_logical_ram_width = 32,
		ram_block9a_5.port_b_address_clear = "clear1",
		ram_block9a_5.port_b_address_clock = "clock1",
		ram_block9a_5.port_b_address_width = 11,
		ram_block9a_5.port_b_data_out_clear = "clear1",
		ram_block9a_5.port_b_data_out_clock = "clock1",
		ram_block9a_5.port_b_data_width = 1,
		ram_block9a_5.port_b_first_address = 0,
		ram_block9a_5.port_b_first_bit_number = 5,
		ram_block9a_5.port_b_last_address = 2047,
		ram_block9a_5.port_b_logical_ram_depth = 2048,
		ram_block9a_5.port_b_logical_ram_width = 8,
		ram_block9a_5.port_b_read_enable_clock = "clock1",
		ram_block9a_5.ram_block_type = "AUTO",
		ram_block9a_5.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block9a_6
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[8:0]}),
	.portadatain({data_a[30], data_a[22], data_a[14], data_a[6]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[10:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block9a_6portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block9a_6.clk0_core_clock_enable = "ena0",
		ram_block9a_6.clk0_input_clock_enable = "none",
		ram_block9a_6.clk1_core_clock_enable = "none",
		ram_block9a_6.clk1_input_clock_enable = "none",
		ram_block9a_6.clk1_output_clock_enable = "ena1",
		ram_block9a_6.connectivity_checking = "OFF",
		ram_block9a_6.data_interleave_offset_in_bits = 8,
		ram_block9a_6.data_interleave_width_in_bits = 1,
		ram_block9a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block9a_6.mixed_port_feed_through_mode = "dont_care",
		ram_block9a_6.operation_mode = "dual_port",
		ram_block9a_6.port_a_address_width = 9,
		ram_block9a_6.port_a_data_width = 4,
		ram_block9a_6.port_a_first_address = 0,
		ram_block9a_6.port_a_first_bit_number = 6,
		ram_block9a_6.port_a_last_address = 511,
		ram_block9a_6.port_a_logical_ram_depth = 512,
		ram_block9a_6.port_a_logical_ram_width = 32,
		ram_block9a_6.port_b_address_clear = "clear1",
		ram_block9a_6.port_b_address_clock = "clock1",
		ram_block9a_6.port_b_address_width = 11,
		ram_block9a_6.port_b_data_out_clear = "clear1",
		ram_block9a_6.port_b_data_out_clock = "clock1",
		ram_block9a_6.port_b_data_width = 1,
		ram_block9a_6.port_b_first_address = 0,
		ram_block9a_6.port_b_first_bit_number = 6,
		ram_block9a_6.port_b_last_address = 2047,
		ram_block9a_6.port_b_logical_ram_depth = 2048,
		ram_block9a_6.port_b_logical_ram_width = 8,
		ram_block9a_6.port_b_read_enable_clock = "clock1",
		ram_block9a_6.ram_block_type = "AUTO",
		ram_block9a_6.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block9a_7
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[8:0]}),
	.portadatain({data_a[31], data_a[23], data_a[15], data_a[7]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[10:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block9a_7portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block9a_7.clk0_core_clock_enable = "ena0",
		ram_block9a_7.clk0_input_clock_enable = "none",
		ram_block9a_7.clk1_core_clock_enable = "none",
		ram_block9a_7.clk1_input_clock_enable = "none",
		ram_block9a_7.clk1_output_clock_enable = "ena1",
		ram_block9a_7.connectivity_checking = "OFF",
		ram_block9a_7.data_interleave_offset_in_bits = 8,
		ram_block9a_7.data_interleave_width_in_bits = 1,
		ram_block9a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block9a_7.mixed_port_feed_through_mode = "dont_care",
		ram_block9a_7.operation_mode = "dual_port",
		ram_block9a_7.port_a_address_width = 9,
		ram_block9a_7.port_a_data_width = 4,
		ram_block9a_7.port_a_first_address = 0,
		ram_block9a_7.port_a_first_bit_number = 7,
		ram_block9a_7.port_a_last_address = 511,
		ram_block9a_7.port_a_logical_ram_depth = 512,
		ram_block9a_7.port_a_logical_ram_width = 32,
		ram_block9a_7.port_b_address_clear = "clear1",
		ram_block9a_7.port_b_address_clock = "clock1",
		ram_block9a_7.port_b_address_width = 11,
		ram_block9a_7.port_b_data_out_clear = "clear1",
		ram_block9a_7.port_b_data_out_clock = "clock1",
		ram_block9a_7.port_b_data_width = 1,
		ram_block9a_7.port_b_first_address = 0,
		ram_block9a_7.port_b_first_bit_number = 7,
		ram_block9a_7.port_b_last_address = 2047,
		ram_block9a_7.port_b_logical_ram_depth = 2048,
		ram_block9a_7.port_b_logical_ram_width = 8,
		ram_block9a_7.port_b_read_enable_clock = "clock1",
		ram_block9a_7.ram_block_type = "AUTO",
		ram_block9a_7.lpm_type = "cycloneive_ram_block";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_b = {wire_ram_block9a_7portbdataout[0], wire_ram_block9a_6portbdataout[0], wire_ram_block9a_5portbdataout[0], wire_ram_block9a_4portbdataout[0], wire_ram_block9a_3portbdataout[0], wire_ram_block9a_2portbdataout[0], wire_ram_block9a_1portbdataout[0], wire_ram_block9a_0portbdataout[0]};
endmodule //fifo_32w8r_altsyncram


//dffpipe DELAY=1 WIDTH=10 clock clrn d ALTERA_INTERNAL_OPTIONS=X_ON_VIOLATION_OPTION=OFF
//VERSION_BEGIN 13.1 cbx_a_gray2bin 2013:10:23:18:05:48:SJ cbx_a_graycounter 2013:10:23:18:05:48:SJ cbx_altdpram 2013:10:23:18:05:48:SJ cbx_altsyncram 2013:10:23:18:05:48:SJ cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_dcfifo 2013:10:23:18:05:48:SJ cbx_fifo_common 2013:10:23:18:05:48:SJ cbx_lpm_add_sub 2013:10:23:18:05:48:SJ cbx_lpm_compare 2013:10:23:18:05:48:SJ cbx_lpm_counter 2013:10:23:18:05:48:SJ cbx_lpm_decode 2013:10:23:18:05:48:SJ cbx_lpm_mux 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_scfifo 2013:10:23:18:05:48:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ cbx_stratixiii 2013:10:23:18:05:48:SJ cbx_stratixv 2013:10:23:18:05:48:SJ cbx_util_mgl 2013:10:23:18:05:48:SJ  VERSION_END


//dffpipe DELAY=1 WIDTH=10 clock clrn d q ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 13.1 cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratixii 2013:10:23:18:05:48:SJ cbx_util_mgl 2013:10:23:18:05:48:SJ  VERSION_END

//synthesis_resources = reg 10 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF"} *)
module  fifo_32w8r_dffpipe
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [9:0]  d;
	output   [9:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[9:0]	dffe11a;
	wire ena;
	wire prn;
	wire sclr;

	// synopsys translate_off
	initial
		dffe11a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe11a <= {10{1'b1}};
		else if (clrn == 1'b0) dffe11a <= 10'b0;
		else if  (ena == 1'b1)   dffe11a <= (d & {10{(~ sclr)}});
	assign
		ena = 1'b1,
		prn = 1'b1,
		q = dffe11a,
		sclr = 1'b0;
endmodule //fifo_32w8r_dffpipe

//synthesis_resources = reg 10 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"X_ON_VIOLATION_OPTION=OFF"} *)
module  fifo_32w8r_alt_synch_pipe
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [9:0]  d;
	output   [9:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [9:0]   wire_dffpipe10_q;

	fifo_32w8r_dffpipe   dffpipe10
	( 
	.clock(clock),
	.clrn(clrn),
	.d(d),
	.q(wire_dffpipe10_q));
	assign
		q = wire_dffpipe10_q;
endmodule //fifo_32w8r_alt_synch_pipe


//dffpipe DELAY=2 WIDTH=1 clock clrn d q ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF;suppress_da_rule_internal=S102
//VERSION_BEGIN 13.1 cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratixii 2013:10:23:18:05:48:SJ cbx_util_mgl 2013:10:23:18:05:48:SJ  VERSION_END

//synthesis_resources = reg 2 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF;suppress_da_rule_internal=S102"} *)
module  fifo_32w8r_dffpipe1
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [0:0]  d;
	output   [0:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[0:0]	dffe12a;
	reg	[0:0]	dffe13a;
	wire ena;
	wire prn;
	wire sclr;

	// synopsys translate_off
	initial
		dffe12a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe12a <= {1{1'b1}};
		else if (clrn == 1'b0) dffe12a <= 1'b0;
		else if  (ena == 1'b1)   dffe12a <= (d & (~ sclr));
	// synopsys translate_off
	initial
		dffe13a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe13a <= {1{1'b1}};
		else if (clrn == 1'b0) dffe13a <= 1'b0;
		else if  (ena == 1'b1)   dffe13a <= (dffe12a & (~ sclr));
	assign
		ena = 1'b1,
		prn = 1'b1,
		q = dffe13a,
		sclr = 1'b0;
endmodule //fifo_32w8r_dffpipe1


//dffpipe DELAY=1 WIDTH=10 clock clrn d q ALTERA_INTERNAL_OPTIONS=X_ON_VIOLATION_OPTION=OFF
//VERSION_BEGIN 13.1 cbx_a_gray2bin 2013:10:23:18:05:48:SJ cbx_a_graycounter 2013:10:23:18:05:48:SJ cbx_altdpram 2013:10:23:18:05:48:SJ cbx_altsyncram 2013:10:23:18:05:48:SJ cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_dcfifo 2013:10:23:18:05:48:SJ cbx_fifo_common 2013:10:23:18:05:48:SJ cbx_lpm_add_sub 2013:10:23:18:05:48:SJ cbx_lpm_compare 2013:10:23:18:05:48:SJ cbx_lpm_counter 2013:10:23:18:05:48:SJ cbx_lpm_decode 2013:10:23:18:05:48:SJ cbx_lpm_mux 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_scfifo 2013:10:23:18:05:48:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ cbx_stratixiii 2013:10:23:18:05:48:SJ cbx_stratixv 2013:10:23:18:05:48:SJ cbx_util_mgl 2013:10:23:18:05:48:SJ  VERSION_END


//dffpipe DELAY=1 WIDTH=10 clock clrn d q ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 13.1 cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratixii 2013:10:23:18:05:48:SJ cbx_util_mgl 2013:10:23:18:05:48:SJ  VERSION_END

//synthesis_resources = reg 10 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF"} *)
module  fifo_32w8r_dffpipe12
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [9:0]  d;
	output   [9:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[9:0]	dffe15a;
	wire ena;
	wire prn;
	wire sclr;

	// synopsys translate_off
	initial
		dffe15a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe15a <= {10{1'b1}};
		else if (clrn == 1'b0) dffe15a <= 10'b0;
		else if  (ena == 1'b1)   dffe15a <= (d & {10{(~ sclr)}});
	assign
		ena = 1'b1,
		prn = 1'b1,
		q = dffe15a,
		sclr = 1'b0;
endmodule //fifo_32w8r_dffpipe12

//synthesis_resources = reg 10 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"X_ON_VIOLATION_OPTION=OFF"} *)
module  fifo_32w8r_alt_synch_pipe1
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [9:0]  d;
	output   [9:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [9:0]   wire_dffpipe14_q;

	fifo_32w8r_dffpipe12   dffpipe14
	( 
	.clock(clock),
	.clrn(clrn),
	.d(d),
	.q(wire_dffpipe14_q));
	assign
		q = wire_dffpipe14_q;
endmodule //fifo_32w8r_alt_synch_pipe1


//lpm_add_sub DEVICE_FAMILY="Cyclone IV E" LPM_DIRECTION="SUB" LPM_WIDTH=10 dataa datab result
//VERSION_BEGIN 13.1 cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_lpm_add_sub 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ  VERSION_END


//lpm_compare DEVICE_FAMILY="Cyclone IV E" LPM_WIDTH=5 aeb dataa datab
//VERSION_BEGIN 13.1 cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_lpm_add_sub 2013:10:23:18:05:48:SJ cbx_lpm_compare 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fifo_32w8r_cmpr
	( 
	aeb,
	dataa,
	datab) /* synthesis synthesis_clearbox=1 */;
	output   aeb;
	input   [4:0]  dataa;
	input   [4:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [4:0]  dataa;
	tri0   [4:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  aeb_result_wire;
	wire  [0:0]  aneb_result_wire;
	wire  [12:0]  data_wire;
	wire  eq_wire;

	assign
		aeb = eq_wire,
		aeb_result_wire = (~ aneb_result_wire),
		aneb_result_wire = ((data_wire[0] | data_wire[1]) | data_wire[2]),
		data_wire = {datab[4], dataa[4], datab[3], dataa[3], datab[2], dataa[2], datab[1], dataa[1], datab[0], dataa[0], (data_wire[11] ^ data_wire[12]), ((data_wire[7] ^ data_wire[8]) | (data_wire[9] ^ data_wire[10])), ((data_wire[3] ^ data_wire[4]) | (data_wire[5] ^ data_wire[6]))},
		eq_wire = aeb_result_wire;
endmodule //fifo_32w8r_cmpr


//lpm_compare DEVICE_FAMILY="Cyclone IV E" LPM_WIDTH=10 aeb dataa datab
//VERSION_BEGIN 13.1 cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_lpm_add_sub 2013:10:23:18:05:48:SJ cbx_lpm_compare 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fifo_32w8r_cmpr1
	( 
	aeb,
	dataa,
	datab) /* synthesis synthesis_clearbox=1 */;
	output   aeb;
	input   [9:0]  dataa;
	input   [9:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [9:0]  dataa;
	tri0   [9:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  aeb_result_wire;
	wire  [0:0]  aneb_result_wire;
	wire  [26:0]  data_wire;
	wire  eq_wire;

	assign
		aeb = eq_wire,
		aeb_result_wire = (~ aneb_result_wire),
		aneb_result_wire = (data_wire[0] | data_wire[1]),
		data_wire = {datab[9], dataa[9], datab[8], dataa[8], datab[7], dataa[7], datab[6], dataa[6], datab[5], dataa[5], datab[4], dataa[4], datab[3], dataa[3], datab[2], dataa[2], datab[1], dataa[1], datab[0], dataa[0], ((data_wire[23] ^ data_wire[24]) | (data_wire[25] ^ data_wire[26])), ((data_wire[19] ^ data_wire[20]) | (data_wire[21] ^ data_wire[22])), ((data_wire[15] ^ data_wire[16]) | (data_wire[17] ^ data_wire[18])), ((data_wire[11] ^ data_wire[12]) | (data_wire[13] ^ data_wire[14])), ((data_wire[7] ^ data_wire[8]) | (data_wire[9] ^ data_wire[10])), data_wire[6], (((data_wire[2] | data_wire[3]) | data_wire[4]) | data_wire[5])},
		eq_wire = aeb_result_wire;
endmodule //fifo_32w8r_cmpr1


//lpm_counter DEVICE_FAMILY="Cyclone IV E" lpm_avalue=1 lpm_direction="UP" lpm_port_updown="PORT_UNUSED" lpm_pvalue=1 lpm_width=2 aset clock cnt_en cout q
//VERSION_BEGIN 13.1 cbx_cycloneii 2013:10:23:18:05:48:SJ cbx_lpm_add_sub 2013:10:23:18:05:48:SJ cbx_lpm_compare 2013:10:23:18:05:48:SJ cbx_lpm_counter 2013:10:23:18:05:48:SJ cbx_lpm_decode 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ cbx_stratix 2013:10:23:18:05:48:SJ cbx_stratixii 2013:10:23:18:05:48:SJ  VERSION_END

//synthesis_resources = lut 2 reg 2 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fifo_32w8r_cntr
	( 
	aset,
	clock,
	cnt_en,
	cout,
	q) /* synthesis synthesis_clearbox=1 */;
	input   aset;
	input   clock;
	input   cnt_en;
	output   cout;
	output   [1:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aset;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_counter_comb_bita_0combout;
	wire  [0:0]   wire_counter_comb_bita_1combout;
	wire  [0:0]   wire_counter_comb_bita_0cout;
	wire  [0:0]   wire_counter_comb_bita_1cout;
	wire	[1:0]	wire_counter_reg_bit_d;
	wire	[1:0]	wire_counter_reg_bit_asdata;
	reg	[1:0]	counter_reg_bit;
	wire	[1:0]	wire_counter_reg_bit_ena;
	wire	[1:0]	wire_counter_reg_bit_sload;
	wire  [1:0]  a_val;
	wire  aclr_actual;
	wire clk_en;
	wire  cout_actual;
	wire [1:0]  data;
	wire  external_cin;
	wire  [1:0]  pre_hazard;
	wire  [1:0]  s_val;
	wire  [1:0]  safe_q;
	wire sclr;
	wire sload;
	wire sset;
	wire  time_to_clear;
	wire  updown_dir;

	cycloneive_lcell_comb   counter_comb_bita_0
	( 
	.cin(external_cin),
	.combout(wire_counter_comb_bita_0combout[0:0]),
	.cout(wire_counter_comb_bita_0cout[0:0]),
	.dataa(counter_reg_bit[0]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_0.lut_mask = 16'h5A60,
		counter_comb_bita_0.sum_lutc_input = "cin",
		counter_comb_bita_0.lpm_type = "cycloneive_lcell_comb";
	cycloneive_lcell_comb   counter_comb_bita_1
	( 
	.cin(wire_counter_comb_bita_0cout[0:0]),
	.combout(wire_counter_comb_bita_1combout[0:0]),
	.cout(wire_counter_comb_bita_1cout[0:0]),
	.dataa(counter_reg_bit[1]),
	.datab(updown_dir),
	.datad(1'b1),
	.datac(1'b0)
	);
	defparam
		counter_comb_bita_1.lut_mask = 16'h5A90,
		counter_comb_bita_1.sum_lutc_input = "cin",
		counter_comb_bita_1.lpm_type = "cycloneive_lcell_comb";
	// synopsys translate_off
	initial
		counter_reg_bit[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[0:0] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[0:0] == 1'b1) 
			if (wire_counter_reg_bit_sload[0:0] == 1'b1) counter_reg_bit[0:0] <= wire_counter_reg_bit_asdata[0:0];
			else  counter_reg_bit[0:0] <= wire_counter_reg_bit_d[0:0];
	// synopsys translate_off
	initial
		counter_reg_bit[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[1:1] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[1:1] == 1'b1) 
			if (wire_counter_reg_bit_sload[1:1] == 1'b1) counter_reg_bit[1:1] <= wire_counter_reg_bit_asdata[1:1];
			else  counter_reg_bit[1:1] <= wire_counter_reg_bit_d[1:1];
	assign
		wire_counter_reg_bit_asdata = (a_val ^ ({2{(~ sclr)}} & (({2{sset}} & s_val) | ({2{(~ sset)}} & data)))),
		wire_counter_reg_bit_d = {wire_counter_comb_bita_1combout[0:0], wire_counter_comb_bita_0combout[0:0]};
	assign
		wire_counter_reg_bit_ena = {2{(clk_en & (((cnt_en | sclr) | sset) | sload))}},
		wire_counter_reg_bit_sload = {2{((sclr | sset) | sload)}};
	assign
		a_val = 2'b01,
		aclr_actual = aset,
		clk_en = 1'b1,
		cout = cout_actual,
		cout_actual = (wire_counter_comb_bita_1cout[0:0] | (time_to_clear & updown_dir)),
		data = {2{1'b0}},
		external_cin = 1'b1,
		pre_hazard = counter_reg_bit,
		q = safe_q,
		s_val = {2{1'b1}},
		safe_q = (pre_hazard ^ a_val),
		sclr = 1'b0,
		sload = 1'b0,
		sset = 1'b0,
		time_to_clear = 1'b0,
		updown_dir = 1'b1;
endmodule //fifo_32w8r_cntr


//lpm_mux DEVICE_FAMILY="Cyclone IV E" LPM_SIZE=2 LPM_WIDTH=1 LPM_WIDTHS=1 data result sel
//VERSION_BEGIN 13.1 cbx_lpm_mux 2013:10:23:18:05:48:SJ cbx_mgl 2013:10:23:18:06:54:SJ  VERSION_END

//synthesis_resources = lut 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  fifo_32w8r_mux
	( 
	data,
	result,
	sel) /* synthesis synthesis_clearbox=1 */;
	input   [1:0]  data;
	output   [0:0]  result;
	input   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [1:0]  data;
	tri0   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  result_node;
	wire  [0:0]  sel_node;
	wire  [1:0]  w_data537w;

	assign
		result = result_node,
		result_node = {((sel_node & w_data537w[1]) | ((~ sel_node) & w_data537w[0]))},
		sel_node = {sel[0]},
		w_data537w = {data[1:0]};
endmodule //fifo_32w8r_mux

//synthesis_resources = lut 17 M9K 2 reg 108 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF;REMOVE_DUPLICATE_REGISTERS=OFF;suppress_da_rule_internal=d101;suppress_da_rule_internal=d102;suppress_da_rule_internal=d103;SYNCHRONIZER_IDENTIFICATION=OFF;SYNCHRONIZATION_REGISTER_CHAIN_LENGTH = 1;suppress_da_rule_internal=R105;-name CUT ON -from rdptr_g -to ws_dgrp|fifo_32w8r_dffpipe12:dffpipe14|dffe15a;-name SDC_STATEMENT \"set_false_path -from *rdptr_g* -to *ws_dgrp|fifo_32w8r_dffpipe12:dffpipe14|dffe15a* \""} *)
module  fifo_32w8r_dcfifo
	( 
	aclr,
	data,
	q,
	rdclk,
	rdreq,
	wrclk,
	wrempty,
	wrfull,
	wrreq,
	wrusedw) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   [31:0]  data;
	output   [7:0]  q;
	input   rdclk;
	input   rdreq;
	input   wrclk;
	output   wrempty;
	output   wrfull;
	input   wrreq;
	output   [8:0]  wrusedw;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [9:0]   wire_wrptr_g_gray2bin_bin;
	wire  [9:0]   wire_ws_dgrp_gray2bin_bin;
	wire  [9:0]   wire_rdptr_g1p_q;
	wire  [9:0]   wire_wrptr_g1p_q;
	wire  [7:0]   wire_fifo_ram_q_b;
	reg	[9:0]	delayed_wrptr_g;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	rdemp_eq_comp_lsb_aeb;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	rdemp_eq_comp_msb_aeb;
	reg	[1:0]	rdptr_b;
	reg	[9:0]	rdptr_g;
	reg	wrfull_eq_comp_lsb_mux_reg;
	reg	wrfull_eq_comp_msb_mux_reg;
	(* ALTERA_ATTRIBUTE = {"suppress_da_rule_internal=S102"} *)
	reg	[9:0]	wrptr_g;
	wire  [9:0]   wire_rs_dgwp_q;
	wire  [0:0]   wire_wraclr_q;
	wire  [9:0]   wire_ws_brp_q;
	wire  [9:0]   wire_ws_bwp_q;
	wire  [9:0]   wire_ws_dgrp_q;
	wire	[9:0]	wire_wrusedw_sub_dataa;
	wire	[9:0]	wire_wrusedw_sub_datab;
	wire	[9:0]	wire_wrusedw_sub_result;
	wire  wire_rdempty_eq_comp1_lsb_aeb;
	wire  wire_rdempty_eq_comp1_msb_aeb;
	wire  wire_rdempty_eq_comp_lsb_aeb;
	wire  wire_rdempty_eq_comp_msb_aeb;
	wire  wire_wrempty_eq_comp_aeb;
	wire  wire_wrfull_eq_comp1_lsb_aeb;
	wire  wire_wrfull_eq_comp1_msb_aeb;
	wire  wire_wrfull_eq_comp_lsb_aeb;
	wire  wire_wrfull_eq_comp_msb_aeb;
	wire  wire_cntr_b_cout;
	wire  [1:0]   wire_cntr_b_q;
	wire  [0:0]   wire_rdemp_eq_comp_lsb_mux_result;
	wire  [0:0]   wire_rdemp_eq_comp_msb_mux_result;
	wire  [0:0]   wire_wrfull_eq_comp_lsb_mux_result;
	wire  [0:0]   wire_wrfull_eq_comp_msb_mux_result;
	wire  int_rdempty;
	wire  int_wrfull;
	wire  [8:0]  ram_address_a;
	wire  [10:0]  ram_address_b;
	wire  valid_rdreq;
	wire  valid_wrreq;
	wire  [9:0]  wrptr_g1s;
	wire  [9:0]  wrptr_gs;

	fifo_32w8r_a_gray2bin   wrptr_g_gray2bin
	( 
	.bin(wire_wrptr_g_gray2bin_bin),
	.gray(wrptr_g));
	fifo_32w8r_a_gray2bin   ws_dgrp_gray2bin
	( 
	.bin(wire_ws_dgrp_gray2bin_bin),
	.gray(wire_ws_dgrp_q));
	fifo_32w8r_a_graycounter   rdptr_g1p
	( 
	.aclr(aclr),
	.clock(rdclk),
	.cnt_en((valid_rdreq & wire_cntr_b_cout)),
	.q(wire_rdptr_g1p_q));
	fifo_32w8r_a_graycounter1   wrptr_g1p
	( 
	.aclr((~ wire_wraclr_q)),
	.clock(wrclk),
	.cnt_en(valid_wrreq),
	.q(wire_wrptr_g1p_q));
	fifo_32w8r_altsyncram   fifo_ram
	( 
	.aclr1(aclr),
	.address_a(ram_address_a),
	.address_b(ram_address_b),
	.addressstall_b((~ valid_rdreq)),
	.clock0(wrclk),
	.clock1(rdclk),
	.clocken1(valid_rdreq),
	.data_a(data),
	.q_b(wire_fifo_ram_q_b),
	.wren_a(valid_wrreq));
	// synopsys translate_off
	initial
		delayed_wrptr_g = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  negedge wire_wraclr_q)
		if (wire_wraclr_q == 1'b0) delayed_wrptr_g <= 10'b0;
		else  delayed_wrptr_g <= wrptr_g;
	// synopsys translate_off
	initial
		rdemp_eq_comp_lsb_aeb = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdemp_eq_comp_lsb_aeb <= {1{1'b1}};
		else  rdemp_eq_comp_lsb_aeb <= wire_rdemp_eq_comp_lsb_mux_result;
	// synopsys translate_off
	initial
		rdemp_eq_comp_msb_aeb = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdemp_eq_comp_msb_aeb <= {1{1'b1}};
		else  rdemp_eq_comp_msb_aeb <= wire_rdemp_eq_comp_msb_mux_result;
	// synopsys translate_off
	initial
		rdptr_b = 0;
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdptr_b <= 2'b0;
		else if  (valid_rdreq == 1'b1)   rdptr_b <= wire_cntr_b_q;
	// synopsys translate_off
	initial
		rdptr_g = 0;
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdptr_g <= 10'b0;
		else if  (valid_rdreq == 1'b1)   rdptr_g <= wire_rdptr_g1p_q;
	// synopsys translate_off
	initial
		wrfull_eq_comp_lsb_mux_reg = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  negedge wire_wraclr_q)
		if (wire_wraclr_q == 1'b0) wrfull_eq_comp_lsb_mux_reg <= 1'b0;
		else  wrfull_eq_comp_lsb_mux_reg <= wire_wrfull_eq_comp_lsb_mux_result;
	// synopsys translate_off
	initial
		wrfull_eq_comp_msb_mux_reg = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  negedge wire_wraclr_q)
		if (wire_wraclr_q == 1'b0) wrfull_eq_comp_msb_mux_reg <= 1'b0;
		else  wrfull_eq_comp_msb_mux_reg <= wire_wrfull_eq_comp_msb_mux_result;
	// synopsys translate_off
	initial
		wrptr_g = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  negedge wire_wraclr_q)
		if (wire_wraclr_q == 1'b0) wrptr_g <= 10'b0;
		else if  (valid_wrreq == 1'b1)   wrptr_g <= wire_wrptr_g1p_q;
	fifo_32w8r_alt_synch_pipe   rs_dgwp
	( 
	.clock(rdclk),
	.clrn((~ aclr)),
	.d(delayed_wrptr_g),
	.q(wire_rs_dgwp_q));
	fifo_32w8r_dffpipe1   wraclr
	( 
	.clock(wrclk),
	.clrn((~ aclr)),
	.d(1'b1),
	.q(wire_wraclr_q));
	fifo_32w8r_dffpipe   ws_brp
	( 
	.clock(wrclk),
	.clrn(wire_wraclr_q),
	.d(wire_ws_dgrp_gray2bin_bin),
	.q(wire_ws_brp_q));
	fifo_32w8r_dffpipe   ws_bwp
	( 
	.clock(wrclk),
	.clrn(wire_wraclr_q),
	.d(wire_wrptr_g_gray2bin_bin),
	.q(wire_ws_bwp_q));
	fifo_32w8r_alt_synch_pipe1   ws_dgrp
	( 
	.clock(wrclk),
	.clrn(wire_wraclr_q),
	.d(rdptr_g),
	.q(wire_ws_dgrp_q));
	assign
		wire_wrusedw_sub_result = wire_wrusedw_sub_dataa - wire_wrusedw_sub_datab;
	assign
		wire_wrusedw_sub_dataa = wire_ws_bwp_q,
		wire_wrusedw_sub_datab = wire_ws_brp_q;
	fifo_32w8r_cmpr   rdempty_eq_comp1_lsb
	( 
	.aeb(wire_rdempty_eq_comp1_lsb_aeb),
	.dataa(delayed_wrptr_g[4:0]),
	.datab(wire_rdptr_g1p_q[4:0]));
	fifo_32w8r_cmpr   rdempty_eq_comp1_msb
	( 
	.aeb(wire_rdempty_eq_comp1_msb_aeb),
	.dataa(delayed_wrptr_g[9:5]),
	.datab(wire_rdptr_g1p_q[9:5]));
	fifo_32w8r_cmpr   rdempty_eq_comp_lsb
	( 
	.aeb(wire_rdempty_eq_comp_lsb_aeb),
	.dataa(delayed_wrptr_g[4:0]),
	.datab(rdptr_g[4:0]));
	fifo_32w8r_cmpr   rdempty_eq_comp_msb
	( 
	.aeb(wire_rdempty_eq_comp_msb_aeb),
	.dataa(delayed_wrptr_g[9:5]),
	.datab(rdptr_g[9:5]));
	fifo_32w8r_cmpr1   wrempty_eq_comp
	( 
	.aeb(wire_wrempty_eq_comp_aeb),
	.dataa(wire_ws_dgrp_q),
	.datab(wrptr_g));
	fifo_32w8r_cmpr   wrfull_eq_comp1_lsb
	( 
	.aeb(wire_wrfull_eq_comp1_lsb_aeb),
	.dataa(rdptr_g[4:0]),
	.datab(wrptr_g1s[4:0]));
	fifo_32w8r_cmpr   wrfull_eq_comp1_msb
	( 
	.aeb(wire_wrfull_eq_comp1_msb_aeb),
	.dataa(rdptr_g[9:5]),
	.datab(wrptr_g1s[9:5]));
	fifo_32w8r_cmpr   wrfull_eq_comp_lsb
	( 
	.aeb(wire_wrfull_eq_comp_lsb_aeb),
	.dataa(rdptr_g[4:0]),
	.datab(wrptr_gs[4:0]));
	fifo_32w8r_cmpr   wrfull_eq_comp_msb
	( 
	.aeb(wire_wrfull_eq_comp_msb_aeb),
	.dataa(rdptr_g[9:5]),
	.datab(wrptr_gs[9:5]));
	fifo_32w8r_cntr   cntr_b
	( 
	.aset(aclr),
	.clock(rdclk),
	.cnt_en(valid_rdreq),
	.cout(wire_cntr_b_cout),
	.q(wire_cntr_b_q));
	fifo_32w8r_mux   rdemp_eq_comp_lsb_mux
	( 
	.data({wire_rdempty_eq_comp1_lsb_aeb, wire_rdempty_eq_comp_lsb_aeb}),
	.result(wire_rdemp_eq_comp_lsb_mux_result),
	.sel(valid_rdreq));
	fifo_32w8r_mux   rdemp_eq_comp_msb_mux
	( 
	.data({wire_rdempty_eq_comp1_msb_aeb, wire_rdempty_eq_comp_msb_aeb}),
	.result(wire_rdemp_eq_comp_msb_mux_result),
	.sel(valid_rdreq));
	fifo_32w8r_mux   wrfull_eq_comp_lsb_mux
	( 
	.data({wire_wrfull_eq_comp1_lsb_aeb, wire_wrfull_eq_comp_lsb_aeb}),
	.result(wire_wrfull_eq_comp_lsb_mux_result),
	.sel(valid_wrreq));
	fifo_32w8r_mux   wrfull_eq_comp_msb_mux
	( 
	.data({wire_wrfull_eq_comp1_msb_aeb, wire_wrfull_eq_comp_msb_aeb}),
	.result(wire_wrfull_eq_comp_msb_mux_result),
	.sel(valid_wrreq));
	assign
		int_rdempty = (rdemp_eq_comp_lsb_aeb & rdemp_eq_comp_msb_aeb),
		int_wrfull = (wrfull_eq_comp_lsb_mux_reg & wrfull_eq_comp_msb_mux_reg),
		q = wire_fifo_ram_q_b,
		ram_address_a = {(wrptr_g[9] ^ wrptr_g[8]), wrptr_g[7:0]},
		ram_address_b = {(wire_rdptr_g1p_q[9] ^ wire_rdptr_g1p_q[8]), wire_rdptr_g1p_q[7:0], wire_cntr_b_q},
		valid_rdreq = (rdreq & (~ int_rdempty)),
		valid_wrreq = (wrreq & (~ (int_wrfull | (~ wire_wraclr_q)))),
		wrempty = wire_wrempty_eq_comp_aeb,
		wrfull = (int_wrfull | (~ wire_wraclr_q)),
		wrptr_g1s = {(~ wire_wrptr_g1p_q[9]), (~ wire_wrptr_g1p_q[8]), wire_wrptr_g1p_q[7:0]},
		wrptr_gs = {(~ wrptr_g[9]), (~ wrptr_g[8]), wrptr_g[7:0]},
		wrusedw = {wire_wrusedw_sub_result[8:0]};
endmodule //fifo_32w8r_dcfifo
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module fifo_32w8r (
	aclr,
	data,
	rdclk,
	rdreq,
	wrclk,
	wrreq,
	q,
	wrempty,
	wrfull,
	wrusedw)/* synthesis synthesis_clearbox = 1 */;

	input	  aclr;
	input	[31:0]  data;
	input	  rdclk;
	input	  rdreq;
	input	  wrclk;
	input	  wrreq;
	output	[7:0]  q;
	output	  wrempty;
	output	  wrfull;
	output	[8:0]  wrusedw;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0	  aclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  sub_wire0;
	wire  sub_wire1;
	wire [7:0] sub_wire2;
	wire [8:0] sub_wire3;
	wire  wrempty = sub_wire0;
	wire  wrfull = sub_wire1;
	wire [7:0] q = sub_wire2[7:0];
	wire [8:0] wrusedw = sub_wire3[8:0];

	fifo_32w8r_dcfifo	fifo_32w8r_dcfifo_component (
				.rdclk (rdclk),
				.wrclk (wrclk),
				.wrreq (wrreq),
				.aclr (aclr),
				.data (data),
				.rdreq (rdreq),
				.wrempty (sub_wire0),
				.wrfull (sub_wire1),
				.q (sub_wire2),
				.wrusedw (sub_wire3));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: AlmostEmpty NUMERIC "0"
// Retrieval info: PRIVATE: AlmostEmptyThr NUMERIC "-1"
// Retrieval info: PRIVATE: AlmostFull NUMERIC "0"
// Retrieval info: PRIVATE: AlmostFullThr NUMERIC "-1"
// Retrieval info: PRIVATE: CLOCKS_ARE_SYNCHRONIZED NUMERIC "1"
// Retrieval info: PRIVATE: Clock NUMERIC "4"
// Retrieval info: PRIVATE: Depth NUMERIC "512"
// Retrieval info: PRIVATE: Empty NUMERIC "1"
// Retrieval info: PRIVATE: Full NUMERIC "1"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: PRIVATE: LE_BasedFIFO NUMERIC "0"
// Retrieval info: PRIVATE: LegacyRREQ NUMERIC "1"
// Retrieval info: PRIVATE: MAX_DEPTH_BY_9 NUMERIC "0"
// Retrieval info: PRIVATE: OVERFLOW_CHECKING NUMERIC "0"
// Retrieval info: PRIVATE: Optimize NUMERIC "2"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: UNDERFLOW_CHECKING NUMERIC "0"
// Retrieval info: PRIVATE: UsedW NUMERIC "1"
// Retrieval info: PRIVATE: Width NUMERIC "32"
// Retrieval info: PRIVATE: dc_aclr NUMERIC "1"
// Retrieval info: PRIVATE: diff_widths NUMERIC "1"
// Retrieval info: PRIVATE: msb_usedw NUMERIC "0"
// Retrieval info: PRIVATE: output_width NUMERIC "8"
// Retrieval info: PRIVATE: rsEmpty NUMERIC "0"
// Retrieval info: PRIVATE: rsFull NUMERIC "0"
// Retrieval info: PRIVATE: rsUsedW NUMERIC "0"
// Retrieval info: PRIVATE: sc_aclr NUMERIC "0"
// Retrieval info: PRIVATE: sc_sclr NUMERIC "0"
// Retrieval info: PRIVATE: wsEmpty NUMERIC "1"
// Retrieval info: PRIVATE: wsFull NUMERIC "1"
// Retrieval info: PRIVATE: wsUsedW NUMERIC "1"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: CONSTANT: LPM_NUMWORDS NUMERIC "512"
// Retrieval info: CONSTANT: LPM_SHOWAHEAD STRING "OFF"
// Retrieval info: CONSTANT: LPM_TYPE STRING "dcfifo_mixed_widths"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "32"
// Retrieval info: CONSTANT: LPM_WIDTHU NUMERIC "9"
// Retrieval info: CONSTANT: LPM_WIDTHU_R NUMERIC "11"
// Retrieval info: CONSTANT: LPM_WIDTH_R NUMERIC "8"
// Retrieval info: CONSTANT: OVERFLOW_CHECKING STRING "ON"
// Retrieval info: CONSTANT: RDSYNC_DELAYPIPE NUMERIC "3"
// Retrieval info: CONSTANT: READ_ACLR_SYNCH STRING "OFF"
// Retrieval info: CONSTANT: UNDERFLOW_CHECKING STRING "ON"
// Retrieval info: CONSTANT: USE_EAB STRING "ON"
// Retrieval info: CONSTANT: WRITE_ACLR_SYNCH STRING "ON"
// Retrieval info: CONSTANT: WRSYNC_DELAYPIPE NUMERIC "3"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT GND "aclr"
// Retrieval info: USED_PORT: data 0 0 32 0 INPUT NODEFVAL "data[31..0]"
// Retrieval info: USED_PORT: q 0 0 8 0 OUTPUT NODEFVAL "q[7..0]"
// Retrieval info: USED_PORT: rdclk 0 0 0 0 INPUT NODEFVAL "rdclk"
// Retrieval info: USED_PORT: rdreq 0 0 0 0 INPUT NODEFVAL "rdreq"
// Retrieval info: USED_PORT: wrclk 0 0 0 0 INPUT NODEFVAL "wrclk"
// Retrieval info: USED_PORT: wrempty 0 0 0 0 OUTPUT NODEFVAL "wrempty"
// Retrieval info: USED_PORT: wrfull 0 0 0 0 OUTPUT NODEFVAL "wrfull"
// Retrieval info: USED_PORT: wrreq 0 0 0 0 INPUT NODEFVAL "wrreq"
// Retrieval info: USED_PORT: wrusedw 0 0 9 0 OUTPUT NODEFVAL "wrusedw[8..0]"
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: CONNECT: @data 0 0 32 0 data 0 0 32 0
// Retrieval info: CONNECT: @rdclk 0 0 0 0 rdclk 0 0 0 0
// Retrieval info: CONNECT: @rdreq 0 0 0 0 rdreq 0 0 0 0
// Retrieval info: CONNECT: @wrclk 0 0 0 0 wrclk 0 0 0 0
// Retrieval info: CONNECT: @wrreq 0 0 0 0 wrreq 0 0 0 0
// Retrieval info: CONNECT: q 0 0 8 0 @q 0 0 8 0
// Retrieval info: CONNECT: wrempty 0 0 0 0 @wrempty 0 0 0 0
// Retrieval info: CONNECT: wrfull 0 0 0 0 @wrfull 0 0 0 0
// Retrieval info: CONNECT: wrusedw 0 0 9 0 @wrusedw 0 0 9 0
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo_32w8r.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo_32w8r.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo_32w8r.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo_32w8r.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo_32w8r_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo_32w8r_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL fifo_32w8r_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
